package provider

import (
	"github.com/selefra/selefra-provider-gcp/table_schema_generator"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/aiplatform"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/apigateway"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/apikeys"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/appengine"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/artifactregistry"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/baremetalsolution"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/batch"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/beyondcorp"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/bigquery"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/billing"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/binaryauthorization"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/certificatemanager"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/clouddeploy"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/clouderrorreporting"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/cloudiot"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/cloudscheduler"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/cloudsupport"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/compute"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/container"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/containeranalysis"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/dns"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/domains"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/functions"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/iam"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/kms"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/livestream"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/logging"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/monitoring"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/redis"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/resourcemanager"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/run"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/secretmanager"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/securitycenter"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/serviceusage"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/sql"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/storage"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/translate"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/videotranscoder"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/vision"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/vmmigration"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/vpcaccess"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/websecurityscanner"
	"github.com/selefra/selefra-provider-gcp/table_schema_generator_tables/workflows"
	"github.com/selefra/selefra-provider-sdk/provider/schema"
)

func GenTables() []*schema.Table {
	return []*schema.Table{
		table_schema_generator.GenTableSchema(&resourcemanager.TableGcpResourcemanagerProjectPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&resourcemanager.TableGcpResourcemanagerFoldersGenerator{}),
		table_schema_generator.GenTableSchema(&resourcemanager.TableGcpResourcemanagerProjectsGenerator{}),
		table_schema_generator.GenTableSchema(&videotranscoder.TableGcpVideotranscoderJobsGenerator{}),
		table_schema_generator.GenTableSchema(&videotranscoder.TableGcpVideotranscoderJobTemplatesGenerator{}),
		table_schema_generator.GenTableSchema(&websecurityscanner.TableGcpWebsecurityscannerScanConfigsGenerator{}),
		table_schema_generator.GenTableSchema(&clouddeploy.TableGcpClouddeployDeliveryPipelinesGenerator{}),
		table_schema_generator.GenTableSchema(&clouddeploy.TableGcpClouddeployTargetsGenerator{}),
		table_schema_generator.GenTableSchema(&livestream.TableGcpLivestreamChannelsGenerator{}),
		table_schema_generator.GenTableSchema(&livestream.TableGcpLivestreamInputsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudsupport.TableGcpCloudsupportCasesGenerator{}),
		table_schema_generator.GenTableSchema(&dns.TableGcpDnsManagedZonesGenerator{}),
		table_schema_generator.GenTableSchema(&dns.TableGcpDnsPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&workflows.TableGcpWorkflowsWorkflowsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformIndexLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformPipelineLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformDatasetLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformModelLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformEndpointLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformVizierLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformIndexendpointLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformMetadataLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformOperationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformTensorboardLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformSpecialistpoolLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformFeaturestoreLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&aiplatform.TableGcpAiplatformJobLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&beyondcorp.TableGcpBeyondcorpAppConnectionsGenerator{}),
		table_schema_generator.GenTableSchema(&beyondcorp.TableGcpBeyondcorpAppGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&beyondcorp.TableGcpBeyondcorpClientGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&beyondcorp.TableGcpBeyondcorpAppConnectorsGenerator{}),
		table_schema_generator.GenTableSchema(&beyondcorp.TableGcpBeyondcorpClientConnectorServicesGenerator{}),
		table_schema_generator.GenTableSchema(&binaryauthorization.TableGcpBinaryauthorizationAssertorsGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeNetworksGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeAutoscalersGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeTargetSslProxiesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeAddressesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeFirewallsGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeDisksGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeBackendServicesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeProjectsGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeSslPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeSubnetworksGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeDiskTypesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeForwardingRulesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeTargetHttpProxiesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeImagesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeUrlMapsGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeSslCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeVpnGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeInterconnectsGenerator{}),
		table_schema_generator.GenTableSchema(&compute.TableGcpComputeInstanceGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&functions.TableGcpFunctionsFunctionsGenerator{}),
		table_schema_generator.GenTableSchema(&monitoring.TableGcpMonitoringAlertPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&appengine.TableGcpAppengineServicesGenerator{}),
		table_schema_generator.GenTableSchema(&appengine.TableGcpAppengineAuthorizedCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&appengine.TableGcpAppengineFirewallIngressRulesGenerator{}),
		table_schema_generator.GenTableSchema(&appengine.TableGcpAppengineAppsGenerator{}),
		table_schema_generator.GenTableSchema(&appengine.TableGcpAppengineAuthorizedDomainsGenerator{}),
		table_schema_generator.GenTableSchema(&appengine.TableGcpAppengineDomainMappingsGenerator{}),
		table_schema_generator.GenTableSchema(&batch.TableGcpBatchJobsGenerator{}),
		table_schema_generator.GenTableSchema(&batch.TableGcpBatchTaskGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&serviceusage.TableGcpServiceusageServicesGenerator{}),
		table_schema_generator.GenTableSchema(&translate.TableGcpTranslateGlossariesGenerator{}),
		table_schema_generator.GenTableSchema(&vmmigration.TableGcpVmmigrationSourcesGenerator{}),
		table_schema_generator.GenTableSchema(&vmmigration.TableGcpVmmigrationTargetProjectsGenerator{}),
		table_schema_generator.GenTableSchema(&vmmigration.TableGcpVmmigrationGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&run.TableGcpRunLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&secretmanager.TableGcpSecretmanagerSecretsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudiot.TableGcpCloudiotDeviceRegistriesGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableGcpIamServiceAccountsGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableGcpIamDenyPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableGcpIamRolesGenerator{}),
		table_schema_generator.GenTableSchema(&redis.TableGcpRedisInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&securitycenter.TableGcpSecuritycenterOrganizationFindingsGenerator{}),
		table_schema_generator.GenTableSchema(&securitycenter.TableGcpSecuritycenterProjectFindingsGenerator{}),
		table_schema_generator.GenTableSchema(&bigquery.TableGcpBigqueryDatasetsGenerator{}),
		table_schema_generator.GenTableSchema(&clouderrorreporting.TableGcpClouderrorreportingErrorGroupStatsGenerator{}),
		table_schema_generator.GenTableSchema(&containeranalysis.TableGcpContaineranalysisOccurrencesGenerator{}),
		table_schema_generator.GenTableSchema(&domains.TableGcpDomainsRegistrationsGenerator{}),
		table_schema_generator.GenTableSchema(&apikeys.TableGcpApikeysKeysGenerator{}),
		table_schema_generator.GenTableSchema(&billing.TableGcpBillingServicesGenerator{}),
		table_schema_generator.GenTableSchema(&billing.TableGcpBillingBillingAccountsGenerator{}),
		table_schema_generator.GenTableSchema(&artifactregistry.TableGcpArtifactregistryLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&vision.TableGcpVisionProductsGenerator{}),
		table_schema_generator.GenTableSchema(&storage.TableGcpStorageBucketsGenerator{}),
		table_schema_generator.GenTableSchema(&vpcaccess.TableGcpVpcaccessLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&certificatemanager.TableGcpCertificatemanagerCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&certificatemanager.TableGcpCertificatemanagerDnsAuthorizationsGenerator{}),
		table_schema_generator.GenTableSchema(&certificatemanager.TableGcpCertificatemanagerCertificateIssuanceConfigsGenerator{}),
		table_schema_generator.GenTableSchema(&certificatemanager.TableGcpCertificatemanagerCertificateMapsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudscheduler.TableGcpCloudschedulerLocationsGenerator{}),
		table_schema_generator.GenTableSchema(&container.TableGcpContainerClustersGenerator{}),
		table_schema_generator.GenTableSchema(&logging.TableGcpLoggingMetricsGenerator{}),
		table_schema_generator.GenTableSchema(&logging.TableGcpLoggingSinksGenerator{}),
		table_schema_generator.GenTableSchema(&sql.TableGcpSqlInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&apigateway.TableGcpApigatewayApisGenerator{}),
		table_schema_generator.GenTableSchema(&apigateway.TableGcpApigatewayGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&baremetalsolution.TableGcpBaremetalsolutionVolumesGenerator{}),
		table_schema_generator.GenTableSchema(&baremetalsolution.TableGcpBaremetalsolutionNetworksGenerator{}),
		table_schema_generator.GenTableSchema(&baremetalsolution.TableGcpBaremetalsolutionNfsSharesGenerator{}),
		table_schema_generator.GenTableSchema(&baremetalsolution.TableGcpBaremetalsolutionInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&kms.TableGcpKmsLocationsGenerator{}),
	}
}
